"""Updated shifts table

Revision ID: 5a11ab400bdc
Revises: 02b945dc81d9
Create Date: 2026-02-28 10:47:53.337507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a11ab400bdc'
down_revision = '02b945dc81d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('break_duration',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('break_duration',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
